#!/bin/bash

set -e
set -u
set -o pipefail

SNAP_VERSION=${SNAP_VERSION:-latest}

mkdir -p /opt/snap/bin
mkdir -p /opt/snap/plugins
mkdir -p /var/log/snap
mkdir -p /etc/snap
mkdir -p /etc/snap/tasks


curl -sfL "https://s3-us-west-2.amazonaws.com/snap.ci.snap-telemetry.io/snap/master/${SNAP_VERSION}/snapd" -o /opt/snap/bin/snapd
curl -sfL "https://s3-us-west-2.amazonaws.com/snap.ci.snap-telemetry.io/snap/master/${SNAP_VERSION}/snapctl" -o /opt/snap/bin/snapctl
chmod 775 /opt/snap/bin/snapd
chmod 775 /opt/snap/bin/snapctl
ln -s /opt/snap/bin/snapd /usr/local/bin/snapd
ln -s /opt/snap/bin/snapctl /usr/local/bin/snapctl

curl -sfL "http://snap.ci.snap-telemetry.io/plugins/snap-plugin-publisher-file/master/latest/linux/x86_64/snap-plugin-publisher-file" -o /opt/snap/plugins/snap-plugin-publisher-file
curl -sfL "http://snap.ci.snap-telemetry.io/plugins/snap-plugin-collector-elasticsearch/latest_build/linux/x86_64/snap-plugin-collector-elasticsearch" -o /opt/snap/plugins/snap-plugin-collector-elasticsearch
curl -sfL "http://snap.ci.snap-telemetry.io/plugins/snap-plugin-publisher-influxdb/latest_build/linux/x86_64/snap-plugin-publisher-influxdb" -o /opt/snap/plugins/snap-plugin-publisher-influxdb
chmod 755 /opt/snap/plugins/snap-plugin-publisher-file
chmod 755 /opt/snap/plugins/snap-plugin-collector-elasticsearch
chmod 755 /opt/snap/plugins/snap-plugin-publisher-influxdb